### ISSUE TITLE
Build with Docker, but couldn't pass~

### ISSUE THREAD

**Issue by bqdmm** [ucbdrive/scalabel#3]
I tried docker building, but with error like:

D:\scalabel-master\scalabel> docker build . -t 'scalabel/server'
Sending build context to Docker daemon    341kB
Step 1/7 : FROM golang
latest: Pulling from library/golang
5847a47b8593: Retrying in 1 second
af675e5054a0: Retrying in 1 second
b0d3f2c48ca5: Download complete
75748857d218: Download complete
19d74f63c372: Download complete
b0eed83ecb53: Download complete
3207ad993a04: Download complete
e49973c4621b: Download complete
fa0cb63db5af: Download complete
995311da59ad: Download complete
c22f9dfd86e1: Download complete
7a8d857661a2: Download complete
a3c0e57fdd68: Download complete
dial tcp 23.41.74.108:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

I have tired sever times and never download '5847a47b8593' and 'af675e5054a0' successfully.

**Comment by AromaticJ** [comment]
Seems my result was better than you @bqdmm , but still couldn't pass...

D:\SDC\label_tool\scalabel\scalabel-master\scalabel> docker build . -t 'scalabel/server'
Sending build context to Docker daemon  9.895MB
Step 1/7 : FROM golang
 ---> 5d512cb863b9
Step 2/7 : EXPOSE 8686
 ---> Using cache
 ---> 37f00aa2c3c2
Step 3/7 : ADD . .
 ---> Using cache
 ---> aee1e75ec7e0
Step 4/7 : RUN echo "---\nport: 8686\ndataDir: \"./data\"\nprojectPath: \".\"\n..."  >> config.yml
 ---> Using cache
 ---> df25edd869eb
Step 5/7 : RUN go get gopkg.in/yaml.v2
 ---> Running in 0dd9243cbc08
# cd C:\gopath\src\gopkg.in\yaml.v2; git submodule update --init --recursive
package gopkg.in/yaml.v2: exit status 66
The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; go get gopkg.in/yaml.v2' returned a non-zero code: 1

**Comment by fyu** [comment]
@bqdmm @AromaticJ From the commands, I can see that both of you are using Windows. We have not tested Scalabel on Windows yet.

**Comment by AromaticJ** [comment]
OK, I tried again. 

Firstly, I open powershell under the dir of scalabel-master which download from github.
for me, it is 'D:\scalabel'.
under this dir, 'README.md', 'LICENSE' and so on...  are contained.

Secondly, I key in command 'go get gopkg.in/yaml.v2'.
Nothing error occured.
powershell log like this:
"""
PS D:\scalabel> go get gopkg.in/yaml.v2
PS D:\scalabel>
"""

Then, I key in command 'go build -i -o $GOPATH/bin/scalabel ./server/go'
powershell log like this:
"""
PS D:\scalabel> go get gopkg.in/yaml.v2
PS D:\scalabel> go build -i -o $GOPATH/bin/scalabel ./server/go
PS D:\scalabel>
"""
Here, for me, the GOPATH has been configured as 'C:\Users\aj\go' in my system environment variables.
so that file 'scalabel' should be generated under dir 'C:\Users\aj\go\bin', but nothing generated.
If I change the command as 'go build -i -o C:\Users\aj\go/bin/scalabel ./server/go' directly.
File 'scalabel' does be generated under dir 'C:\Users\aj\go\bin'.
powershell log like this:
"""
PS D:\scalabel> go get gopkg.in/yaml.v2
PS D:\scalabel> go build -i -o $GOPATH/bin/scalabel ./server/go
PS D:\scalabel> go build -i -o C:\Users\aj\go/bin/scalabel ./server/go
PS D:\scalabel>
"""

Lastly, I key in command 'C:\Users\aj\go/bin/scalabel --config app/config/default_config.yml'
And then win10 ask me to select a program to execute 'scalabel'.
powershell log like this:
"""
PS D:\scalabel> go get gopkg.in/yaml.v2
PS D:\scalabel> go build -i -o $GOPATH/bin/scalabel ./server/go
PS D:\scalabel> go build -i -o C:\Users\aj\go/bin/scalabel ./server/go
PS D:\scalabel> C:\Users\aj\go/bin/scalabel --config app/config/default_config.yml
PS D:\scalabel>
"""

**Comment by seanremy** [comment]
Rename "scalabel" to "scalabel.exe" and try running it.

**Comment by seanremy** [comment]
Closing this issue, as we're working on Windows support in our internal repo and should have a release with it this week.
